CREATE TABLE DEPARTMENT_T (
    DEPT_NO       VARCHAR2(15 BYTE) NOT NULL PRIMARY KEY,
    DEPT_NAME     VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL
);

CREATE TABLE EMPLOYEE_T (
    EMP_NO        NUMBER            NOT NULL PRIMARY KEY,
    DEPT_NO       VARCHAR2(15 BYTE) REFERENCES DEPARTMENT_T(DEPT_NO) ON DELETE SET NULL, -- DEPT NO라는 이름은 달라도 됨(권장하진 않음) VARCHAR2(타입은 같아야함).
    POSITION      CHAR(10 BYTE),
    NAME          VARCHAR2(15 BYTE),
    HIDE_DATE     DATE,
    SALARY        NUMBER
);

CREATE TABLE PROJECT_T (
    PJT_NO        NUMBER NOT NULL PRIMARY KEY,
    PJT_NAME      VARCHAR2(30 BYTE),
    BEGIN_DATE    DATE,
    END_DATE      DATE
);

CREATE TABLE PROCEEDING_T (
    PCD_NO        NUMBER NOT NULL PRIMARY KEY,
    EMP_NO        NUMBER REFERENCES EMPLOYEE_T(EMP_NO) ON DELETE CASCADE,
    PJT_NO        NUMBER REFERENCES PROJECT_T(PJT_NO) ON DELETE SET NULL,
    PJT_STATE     NUMBER NOT NULL
);

DROP TABLE PROCEEDING_T;
DROP TABLE EMPLOYEE_T;
DROP TABLE PROJECT_T;
DROP TABLE DEPARTMENT_T;